# Data Wrangling

In this notebook, we perform data cleaning, fix missing values, and add new columns with meaning values.

## Loading modules

In [1]:
import pandas as pd
import numpy as np

## Loading the data

We acquired the test score data for the [California Assessment of Student Performance and Progress (CAASPP)](https://caaspp.cde.ca.gov/). The data is available between 2015 and 2018.

* [CAASPP test scores](https://caaspp.cde.ca.gov/sb2018/ResearchFileList) 

Additional datasets are obtained in the following sites:
* [Civil Rights Data Collection](https://ocrdata.ed.gov/): Teacher demographics
* [Zillow research data](https://www.zillow.com/research/data/): House prices based on zipcodes
* [GreatSchools API](https://www.greatschools.org/api/docs/technical-overview/): School profile, school reviews, school censuc data, nearby schools

We first load the 2018 test data.

In [2]:
df = pd.read_csv("/Users/ahrimhan/Documents/data_science/Data/sb_ca2018_all_csv_v3/sb_ca2018_all.csv")

In [3]:
df.shape

(3269730, 32)

In [4]:
df.head()

,County Code,District Code,School Code,Filler,Test Year,Subgroup ID,Test Type,Total Tested At Entity Level,Total Tested with Scores,Grade,...,Area 1 Percentage Below Standard,Area 2 Percentage Above Standard,Area 2 Percentage Near Standard,Area 2 Percentage Below Standard,Area 3 Percentage Above Standard,Area 3 Percentage Near Standard,Area 3 Percentage Below Standard,Area 4 Percentage Above Standard,Area 4 Percentage Near Standard,Area 4 Percentage Below Standard
0,0,0,0,NaN,2018,1,B,3180554,3177403,3,...,30.66,23.84,43.30,32.85,20.89,61.25,17.86,27.60,47.71,24.68
1,0,0,0,NaN,2018,1,B,3187375,3184687,3,...,33.21,26.72,42.30,30.98,28.80,46.31,24.89,0.00,0.00,0.00
2,0,0,0,NaN,2018,1,B,3187375,3184687,4,...,39.95,21.65,44.73,33.62,24.03,43.78,32.20,0.00,0.00,0.00
3,0,0,0,NaN,2018,1,B,3180554,3177403,4,...,28.46,24.18,44.21,31.61,19.30,63.22,17.48,25.86,48.83,25.31
4,0,0,0,NaN,2018,1,B,3180554,3177403,5,...,30.76,29.20,41.42,29.38,16.52,59.74,23.73,28.29,44.32,27.39

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3269730 entries, 0 to 3269729
Data columns (total 32 columns):
County Code                          int64
District Code                        int64
School Code                          int64
Filler                               float64
Test Year                            int64
Subgroup ID                          int64
Test Type                            object
Total Tested At Entity Level         object
Total Tested with Scores             object
Grade                                int64
Test Id                              int64
CAASPP Reported Enrollment           object
Students Tested                      object
Mean Scale Score                     object
Percentage Standard Exceeded         object
Percentage Standard Met              object
Percentage Standard Met and Above    object
Percentage Standard Nearly Met       object
Percentage Standard Not Met          object
Students with Scores                 object
Area 1 Percentage Above Standard     object
Area 1 Percentage Near Standard      object
Area 1 Percentage Below Standard     object
Area 2 Percentage Above Standard     object
Area 2 Percentage Near Standard      object
Area 2 Percentage Below Standard     object
Area 3 Percentage Above Standard     object
Area 3 Percentage Near Standard      object
Area 3 Percentage Below Standard     object
Area 4 Percentage Above Standard     object
Area 4 Percentage Near Standard      object
Area 4 Percentage Below Standard     object
dtypes: float64(1), int64(7), object(24)
memory usage: 798.3+ MB

The following entity files list the County, District, and School entity names and codes for all entities as the existed in the administration year selected. This file must be merged with the test data file to join these entity names with the appropriate score data.

In [17]:
import chardet

#find the file encoding type
with open("/Users/ahrimhan/Documents/data_science/Data/sb_ca2018_all_csv_v3/sb_ca2018entities.csv", 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large
    
entities = pd.read_csv("/Users/ahrimhan/Documents/data_science/Data/sb_ca2018_all_csv_v3/sb_ca2018entities.csv", encoding=result['encoding'])

In [18]:
entities.shape

(11333, 10)

In [19]:
entities.head()

,County Code,District Code,School Code,Filler,Test Year,Type Id,County Name,District Name,School Name,Zip Code
0,35,67520,6035109,NaN,2018,7,San Benito,Panoche Elementary,Panoche Elementary,95043
1,35,67538,0,NaN,2018,6,San Benito,San Benito High,NaN,
2,35,67538,3530029,NaN,2018,7,San Benito,San Benito High,San Andreas Continuation High,95023
3,35,67538,3537008,NaN,2018,7,San Benito,San Benito High,San Benito High,95023
4,35,67553,0,NaN,2018,6,San Benito,Southside Elementary,NaN,

Each `Subgroup ID` has the following meanings. We can investigate the characteristics of individual students.

In [36]:
subgroup = pd.read_csv("/Users/ahrimhan/Documents/data_science/Data/Subgroups.txt", header=None)
subgroup.shape

(47, 4)

In [37]:
subgroup.drop(0, axis=1, inplace=True)
subgroup.columns = ['Subgroup ID', 'Student Groups', 'Category']
subgroup.sort_values("Category")
subgroup.head(47)

,Subgroup ID,Student Groups,Category
0,1,"""All Students""","""All Students"""
1,3,"""Male""","""Gender"""
2,4,"""Female""","""Gender"""
3,6,"""Fluent English proficient and English only""","""English-Language Fluency"""
4,7,"""Initial fluent English proficient (IFEP)""","""English-Language Fluency"""
5,8,"""Reclassified fluent English proficient (RFEP)""","""English-Language Fluency"""
6,28,"""Migrant education""","""Migrant"""
7,31,"""Economically disadvantaged""","""Economic Status"""
8,74,"""Black or African American""","""Ethnicity"""
9,75,"""American Indian or Alaska Native""","""Ethnicity"""
10,76,"""Asian""","""Ethnicity"""
11,77,"""Filipino""","""Ethnicity"""
12,78,"""Hispanic or Latino""","""Ethnicity"""
13,79,"""Native Hawaiian or Pacific Islander""","""Ethnicity"""
14,80,"""White""","""Ethnicity"""
15,90,"""Not a high school graduate""","""Parent Education"""
16,91,"""High school graduate""","""Parent Education"""
17,92,"""Some college (includes AA degree)""","""Parent Education"""
18,93,"""College graduate""","""Parent Education"""
19,94,"""Graduate school/Post graduate""","""Parent Education"""
20,99,"""Students with no reported disability""","""Disability Status"""
21,111,"""Not economically disadvantaged""","""Economic Status"""
22,120,"""English learners (ELs) enrolled in school in...","""English-Language Fluency"""
23,121,"""Declined to state""","""Parent Education"""
24,128,"""Students with disability""","""Disability Status"""
25,142,"""English learners enrolled in school in the U...","""English-Language Fluency"""
26,144,"""Two or more races""","""Ethnicity"""
27,160,"""English learner""","""English-Language Fluency"""
28,170,"""Ever-ELs""","""English-Language Fluency"""
29,180,"""English only""","""English-Language Fluency"""
30,190,"""To be determined (TBD)""","""English-Language Fluency"""
31,200,"""Black or African American""","""Ethnicity for Economically Disadvantaged"""
32,201,"""American Indian or Alaska Native""","""Ethnicity for Economically Disadvantaged"""
33,202,"""Asian""","""Ethnicity for Economically Disadvantaged"""
34,203,"""Filipino""","""Ethnicity for Economically Disadvantaged"""
35,204,"""Hispanic or Latino""","""Ethnicity for Economically Disadvantaged"""
36,205,"""Native Hawaiian or Pacific Islander""","""Ethnicity for Economically Disadvantaged"""
37,206,"""White""","""Ethnicity for Economically Disadvantaged"""
38,207,"""Two or more races""","""Ethnicity for Economically Disadvantaged"""
39,220,"""Black or African American""","""Ethnicity for Not Economically Disadvantaged"""
40,221,"""American Indian or Alaska Native""","""Ethnicity for Not Economically Disadvantaged"""
41,222,"""Asian""","""Ethnicity for Not Economically Disadvantaged"""
42,223,"""Filipino""","""Ethnicity for Not Economically Disadvantaged"""
43,224,"""Hispanic or Latino""","""Ethnicity for Not Economically Disadvantaged"""
44,225,"""Native Hawaiian or Pacific Islander""","""Ethnicity for Not Economically Disadvantaged"""
45,226,"""White""","""Ethnicity for Not Economically Disadvantaged"""
46,227,"""Two or more races""","""Ethnicity for Not Economically Disadvantaged"""

For example, if we want the DataFrame where the district is **Irvine Unified**, the ethnicity is **Asian** for the **3rd** grade, we can obtain it as follows.

In [38]:
df.loc[(df['District Code'] == 73650) & (df['Subgroup ID'] == 76) & (df['Grade'] == 3), :]

,County Code,District Code,School Code,Filler,Test Year,Subgroup ID,Test Type,Total Tested At Entity Level,Total Tested with Scores,Grade,...,Area 1 Percentage Below Standard,Area 2 Percentage Above Standard,Area 2 Percentage Near Standard,Area 2 Percentage Below Standard,Area 3 Percentage Above Standard,Area 3 Percentage Near Standard,Area 3 Percentage Below Standard,Area 4 Percentage Above Standard,Area 4 Percentage Near Standard,Area 4 Percentage Below Standard
1602961,30,73650,0,NaN,2018,76,B,8918,8918,3,...,4.61,62.32,32.03,5.64,66.38,28.30,5.33,0.00,0.00,0.00
1602962,30,73650,0,NaN,2018,76,B,8666,8666,3,...,8.84,54.38,35.62,10.00,41.29,53.76,4.95,56.81,35.84,7.35
1603803,30,73650,129155,NaN,2018,76,B,312,312,3,...,4.71,71.76,23.53,4.71,82.35,14.12,3.53,0.00,0.00,0.00
1603804,30,73650,129155,NaN,2018,76,B,301,301,3,...,5.95,76.19,16.67,7.14,53.57,42.86,3.57,75.00,20.24,4.76
1604137,30,73650,129296,NaN,2018,76,B,282,282,3,...,2.82,60.56,38.03,1.41,70.42,28.17,1.41,0.00,0.00,0.00
1604138,30,73650,129296,NaN,2018,76,B,281,281,3,...,4.23,49.30,38.03,12.68,43.66,50.70,5.63,61.97,30.99,7.04
1604465,30,73650,133389,NaN,2018,76,B,267,267,3,...,6.25,53.13,39.06,7.81,54.69,39.06,6.25,0.00,0.00,0.00
1604466,30,73650,133389,NaN,2018,76,B,259,259,3,...,14.29,42.86,41.27,15.87,31.75,58.73,9.52,42.86,44.44,12.70
1604845,30,73650,135137,NaN,2018,76,B,141,141,3,...,7.89,65.79,23.68,10.53,52.63,44.74,2.63,0.00,0.00,0.00
1604846,30,73650,135137,NaN,2018,76,B,118,118,3,...,11.11,52.78,36.11,11.11,22.22,75.00,2.78,52.78,33.33,13.89
1605595,30,73650,3030467,NaN,2018,76,B,14,14,3,...,*,*,*,*,*,*,*,*,*,*
1605596,30,73650,3030467,NaN,2018,76,B,14,14,3,...,*,*,*,*,*,*,*,*,*,*
1606423,30,73650,6030191,NaN,2018,76,B,125,125,3,...,9.52,52.38,38.10,9.52,52.38,23.81,23.81,0.00,0.00,0.00
1606424,30,73650,6030191,NaN,2018,76,B,91,91,3,...,23.53,41.18,23.53,35.29,47.06,41.18,11.76,41.18,41.18,17.65
1606745,30,73650,6068647,NaN,2018,76,B,263,263,3,...,3.45,62.07,34.48,3.45,48.28,50.00,1.72,70.69,24.14,5.17
1606746,30,73650,6068647,NaN,2018,76,B,273,273,3,...,3.39,67.80,28.81,3.39,72.88,23.73,3.39,0.00,0.00,0.00
1607275,30,73650,6085344,NaN,2018,76,B,316,316,3,...,6.33,51.90,43.04,5.06,51.90,39.24,8.86,0.00,0.00,0.00
1607276,30,73650,6085344,NaN,2018,76,B,302,302,3,...,5.33,46.67,38.67,14.67,36.00,58.67,5.33,53.33,38.67,8.00
1607623,30,73650,6089429,NaN,2018,76,B,127,127,3,...,11.11,44.44,38.89,16.67,50.00,36.11,13.89,0.00,0.00,0.00
1607624,30,73650,6089429,NaN,2018,76,B,86,86,3,...,26.09,26.09,26.09,47.83,17.39,69.57,13.04,21.74,73.91,4.35
1607979,30,73650,6089437,NaN,2018,76,B,235,235,3,...,6.35,52.38,39.68,7.94,50.79,42.86,6.35,0.00,0.00,0.00
1607980,30,73650,6089437,NaN,2018,76,B,204,204,3,...,19.61,45.10,35.29,19.61,29.41,62.75,7.84,33.33,50.98,15.69
1608301,30,73650,6089445,NaN,2018,76,B,86,86,3,...,5.56,27.78,66.67,5.56,33.33,66.67,0.00,38.89,61.11,0.00
1608302,30,73650,6089445,NaN,2018,76,B,86,86,3,...,5.56,55.56,44.44,0.00,55.56,44.44,0.00,0.00,0.00,0.00
1608633,30,73650,6094718,NaN,2018,76,B,175,175,3,...,7.14,67.86,21.43,10.71,67.86,28.57,3.57,0.00,0.00,0.00
1608634,30,73650,6094718,NaN,2018,76,B,171,171,3,...,3.70,55.56,44.44,0.00,44.44,55.56,0.00,62.96,25.93,11.11
1609241,30,73650,6096184,NaN,2018,76,B,203,203,3,...,2.38,50.00,42.86,7.14,71.43,26.19,2.38,0.00,0.00,0.00
1609242,30,73650,6096184,NaN,2018,76,B,201,201,3,...,5.00,52.50,37.50,10.00,40.00,57.50,2.50,55.00,40.00,5.00
1609587,30,73650,6096192,NaN,2018,76,B,431,431,3,...,4.92,68.85,29.51,1.64,50.82,45.90,3.28,72.95,23.77,3.28
1609588,30,73650,6096192,NaN,2018,76,B,433,433,3,...,0.82,63.93,35.25,0.82,77.87,18.03,4.10,0.00,0.00,0.00
1609926,30,73650,6096200,NaN,2018,76,B,126,126,3,...,2.50,62.50,35.00,2.50,62.50,35.00,2.50,0.00,0.00,0.00
1609927,30,73650,6096200,NaN,2018,76,B,126,126,3,...,2.50,55.00,40.00,5.00,37.50,60.00,2.50,55.00,37.50,7.50
1610232,30,73650,6097042,NaN,2018,76,B,85,85,3,...,0.00,63.64,36.36,0.00,40.91,54.55,4.55,77.27,22.73,0.00
1610233,30,73650,6097042,NaN,2018,76,B,86,86,3,...,4.55,81.82,18.18,0.00,86.36,13.64,0.00,0.00,0.00,0.00
1610736,30,73650,6098529,NaN,2018,76,B,217,217,3,...,8.33,47.22,44.44,8.33,47.22,44.44,8.33,50.00,38.89,11.11
1610737,30,73650,6098529,NaN,2018,76,B,218,218,3,...,2.78,66.67,25.00,8.33,72.22,19.44,8.33,0.00,0.00,0.00
1611036,30,73650,6100317,NaN,2018,76,B,167,167,3,...,5.26,42.11,36.84,21.05,52.63,31.58,15.79,42.11,47.37,10.53
1611037,30,73650,6100317,NaN,2018,76,B,169,169,3,...,5.00,65.00,35.00,0.00,50.00,35.00,15.00,0.00,0.00,0.00
1611356,30,73650,6100838,NaN,2018,76,B,204,204,3,...,9.09,47.27,43.64,9.09,41.82,52.73,5.45,50.91,38.18,10.91
1611357,30,73650,6100838,NaN,2018,76,B,204,204,3,...,3.64,61.82,30.91,7.27,63.64,29.09,7.27,0.00,0.00,0.00
1611692,30,73650,6100861,NaN,2018,76,B,184,184,3,...,4.65,72.09,20.93,6.98,72.09,23.26,4.65,0.00,0.00,0.00
1611693,30,73650,6100861,NaN,2018,76,B,182,182,3,...,9.52,61.90,30.95,7.14,50.00,50.00,0.00,64.29,33.33,2.38
1612270,30,73650,6102719,NaN,2018,76,B,203,203,3,...,8.82,67.65,29.41,2.94,44.12,52.94,2.94,50.00,50.00,0.00
1612271,30,73650,6102719,NaN,2018,76,B,204,204,3,...,5.88,67.65,26.47,5.88,76.47,20.59,2.94,0.00,0.00,0.00
1612586,30,73650,6106850,NaN,2018,76,B,113,113,3,...,4.55,72.73,22.73,4.55,72.73,22.73,4.55,0.00,0.00,0.00
1612587,30,73650,6106850,NaN,2018,76,B,112,112,3,...,4.55,61.90,38.10,0.00,45.45,45.45,9.09,63.64,31.82,4.55
1612922,30,73650,6107502,NaN,2018,76,B,119,119,3,...,12.12,60.61,30.30,9.09,75.76,12.12,12.12,0.00,0.00,0.00
1612923,30,73650,6107502,NaN,2018,76,B,115,115,3,...,12.12,48.48,36.36,15.15,30.30,66.67,3.03,54.55,33.33,12.12
1613241,30,73650,6108799,NaN,2018,76,B,250,250,3,...,8.00,66.00,26.00,8.00,68.00,30.00,2.00,0.00,0.00,0.00
1613242,30,73650,6108799,NaN,2018,76,B,244,244,3,...,8.51,65.96,29.79,4.26,40.43,59.57,0.00,61.70,36.17,2.13
1613805,30,73650,6115455,NaN,2018,76,B,235,235,3,...,0.00,73.02,23.81,3.17,66.67,28.57,4.76,0.00,0.00,0.00
1613806,30,73650,6115455,NaN,2018,76,B,234,234,3,...,4.76,46.03,46.03,7.94,46.03,50.79,3.17,60.32,36.51,3.17
1614147,30,73650,6115786,NaN,2018,76,B,301,301,3,...,3.33,63.33,35.00,1.67,66.67,31.67,1.67,0.00,0.00,0.00
1614148,30,73650,6115786,NaN,2018,76,B,299,299,3,...,20.00,51.67,38.33,10.00,36.67,55.00,8.33,43.33,48.33,8.33
1614595,30,73650,6120141,NaN,2018,76,B,178,178,3,...,17.65,45.10,37.25,17.65,31.37,58.82,9.80,50.98,33.33,15.69
1614596,30,73650,6120141,NaN,2018,76,B,182,182,3,...,3.85,55.77,30.77,13.46,57.69,34.62,7.69,0.00,0.00,0.00